#!/usr/bin/env bash
cwd=$(pwd)

for i in "$cwd"/files/* ; do
  if [ -d "$i" ]; then
    cd "$i"
    package=$(basename $(pwd))
    echo
    echo "Archive $package files"
    tar --exclude="$package.tar.bz2" --exclude=".DS_Store" --exclude=".." -zcvf "$package.tar.bz2" .
  fi
done

if [[ $1 == "--full" ]]; then
  echo
  echo "I'm going to create full package!"
  cd ../..
  rm -f omg.tar.bz2
  tar -zcvf ../omg.tar.bz2 ./*
fi
