#!/usr/bin/env bash

USERNAME=$1
VAGRANTFILE="$(pwd)/Vagrantfile"
OMG_PATH=$(dirname $0)
SED_EXT='.old'

if [[ ! -z $USERNAME ]]; then
  echo
  echo "User to add: $USERNAME"
  echo "File to modify: $VAGRANTFILE"
  echo

  rm -f $VAGRANTFILE
  rm -f "$VAGRANTFILE.old"

  vagrant init 'chef/ubuntu-13.04'
  vagrant up

  vagrant ssh -c "sudo adduser $USERNAME"
  vagrant ssh -c "sudo adduser $USERNAME sudo"
  vagrant ssh -c "sudo cp -r ~/.ssh/ /home/$USERNAME/"
  vagrant ssh -c "sudo chown -R $USERNAME:$USERNAME /home/$USERNAME/.ssh"

  # * Add: Synced project folder
  sed -i $SED_EXT "15i\\
  \ \ config.vm.synced_folder \"$OMG_PATH\", \"/home/$USERNAME/omg\"" $VAGRANTFILE

  # * Add: config.ssh.username = "username"
  VAGRANT_USER="config.ssh.username = \"$USERNAME\""
  VAGRANT_USER="${VAGRANT_USER//$'\n'/\\$'\n'}"

  #sed -i .old "s/config.ssh.username = \"vagrant\"/$VAGRANT_USER/g" $VAGRANTFILE
  sed -i $SED_EXT "15i\\
  \\
  \ \ $VAGRANT_USER\\
  " $VAGRANTFILE

  # * Add: config.vm.network :public_network # 2nd interface bridged mode
  sed -i $SED_EXT '15i\
  \ \ config.vm.network :public_network' $VAGRANTFILE

  vagrant reload

  if ! grep -q 'vagrant' ~/.ssh/config; then
  SSH_CONFIG=$(vagrant ssh-config --host vagrant)

  # * Add vagrant SSH config to config
  cat >> ~/.ssh/config<<CONF
$SSH_CONFIG
ControlMaster auto
ControlPath ~/.ssh/master-%r@%h:%p
CONF
fi

  vagrant ssh -c '~/omg/install ~/omg/packages.sh'
else
  echo 'Use script like: vagrantup username'
fi

